"""Disposable schema/role setup. Never accept production or a populated database."""

import asyncio
import os
import re
from pathlib import Path
from uuid import UUID, uuid4

import asyncpg
import pytest
from pydantic import SecretStr
from sqlalchemy.engine import make_url

from uranus_research_service.database import SOURCE_TABLES


def uid(i):
    return UUID(int=i)


def guarded_url(value):
    parsed = make_url(value)
    if not parsed.database or not re.fullmatch(r"[a-z][a-z0-9_]*_test", parsed.database):
        raise ValueError("Refusing DDL outside an explicit _test database")
    if parsed.host not in {"localhost", "127.0.0.1", "::1"}:
        raise ValueError("Disposable tests require a loopback database")
    return parsed


AREA_DDL = """CREATE SCHEMA admin;
CREATE TABLE admin.research_area (
 id uuid PRIMARY KEY, area_type text NOT NULL, country_code text NOT NULL,
 region_code text NOT NULL, name text NOT NULL, display_name text NOT NULL,
 osm_type text NOT NULL, osm_id bigint NOT NULL, osm_admin_level integer NOT NULL,
 municipality_key text, population_count integer, population_date date,
 population_source text, population_name text, population_file_sha256 text,
 population_imported_at timestamptz, geometry geometry(MultiPolygon,4326) NOT NULL,
 centroid geometry(Point,4326) NOT NULL, source text NOT NULL,
 retrieved_at timestamptz NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL
);
CREATE TABLE admin.workflow_private (id integer, private_value text);
"""


@pytest.fixture(scope="session")
async def postgres():
    value = os.environ.get("TEST_DATABASE_URL")
    if not value:
        pytest.skip("TEST_DATABASE_URL required for disposable PostGIS tests")
    url = guarded_url(value)
    conn = await asyncpg.connect(value.replace("postgresql+asyncpg://", "postgresql://"))
    if await conn.fetchval(
        "SELECT to_regnamespace('uranus') IS NOT NULL OR to_regnamespace('admin') IS NOT NULL"
    ):
        await conn.close()
        pytest.fail("Refusing existing uranus/admin schemas")
    suffix = uuid4().hex[:10]
    source, area = "research_source_" + suffix, "research_area_" + suffix
    password = "synthetic-reader-password-only"
    try:
        async with conn.transaction():
            await conn.execute(await asyncio.to_thread(Path("tests/fixtures/uranus.sql").read_text))
            await conn.execute(AREA_DDL)
            # Identifiers are generated by this fixture, never caller/model supplied.
            await conn.execute(f'REVOKE CREATE,TEMP ON DATABASE "{url.database}" FROM PUBLIC')
            await conn.execute("REVOKE CREATE ON SCHEMA public FROM PUBLIC")
            for role in (source, area):
                await conn.execute(f"CREATE ROLE {role} LOGIN PASSWORD '{password}'")
            await conn.execute(f"GRANT USAGE ON SCHEMA uranus TO {source}")
            await conn.execute(f"GRANT SELECT ON {','.join(SOURCE_TABLES)} TO {source}")
            await conn.execute(f"GRANT USAGE ON SCHEMA admin TO {area}")
            await conn.execute(f"GRANT SELECT ON admin.research_area TO {area}")
            for i, name in [(10, "Alpha"), (11, "Beta")]:
                await conn.execute(
                    "INSERT INTO uranus.organization(uuid,name) VALUES($1,$2)", uid(i), name
                )
            for i, org, name, x in [(20, 10, "Haus", 9.4), (21, 11, "Dock", 10.4)]:
                await conn.execute(
                    "INSERT INTO uranus.venue(uuid,org_uuid,name,scope,city,point) "
                    "VALUES($1,$2,$3,'organization','Flensburg',"
                    "ST_SetSRID(ST_MakePoint($4,54.8),4326))",
                    uid(i),
                    uid(org),
                    name,
                    x,
                )
            for i, org, venue, title, status in [
                (30, 10, 20, "Jazz im Haus", "released"),
                (31, 11, 21, "Theater am Dock", "released"),
                (32, 10, 20, "Privater Entwurf", "draft"),
            ]:
                await conn.execute(
                    "INSERT INTO uranus.event(uuid,org_uuid,venue_uuid,"
                    "title,release_status,categories) "
                    "VALUES($1,$2,$3,$4,$5,ARRAY[1])",
                    uid(i),
                    uid(org),
                    uid(venue),
                    title,
                    status,
                )
            for i, event, day, hour in [
                (40, 30, 4, 18),
                (41, 30, 5, 20),
                (42, 31, 4, 19),
                (43, 31, 10, 16),
                (44, 32, 4, 18),
            ]:
                await conn.execute(
                    "INSERT INTO uranus.event_date(uuid,event_uuid,start_date,"
                    "start_time,all_day,release_status) "
                    "VALUES($1,$2,make_date(2026,10,$3),make_time($4,0,0),false,'inherited')",
                    uid(i),
                    uid(event),
                    day,
                    hour,
                )
            await conn.execute("INSERT INTO uranus.event_category VALUES(1,'de','Kultur',NULL)")
            await conn.execute(
                "INSERT INTO uranus.event_type VALUES(1,'de','Konzert',NULL),"
                "(2,'de','Theater',NULL)"
            )
            await conn.execute("INSERT INTO uranus.genre_type VALUES('Jazz',1,1,'de')")
            await conn.execute(
                "INSERT INTO uranus.event_type_link VALUES($1,1,1),($2,2,0)", uid(30), uid(31)
            )
            await conn.execute(
                """INSERT INTO admin.research_area(id,area_type,country_code,region_code,
 name,display_name,osm_type,osm_id,osm_admin_level,geometry,centroid,source,
 retrieved_at,created_at,updated_at)
 VALUES($1,'municipality','DE','DE-SH','Flensburg','Flensburg','R',1,8,
 ST_Multi(ST_GeomFromText('POLYGON((9 54,10 54,10 55,9 55,9 54))',4326)),
 ST_SetSRID(ST_MakePoint(9.5,54.5),4326),'osm',now(),now(),now())""",
                uid(90),
            )
        await conn.close()

        def reader(role):
            return url.set(
                drivername="postgresql+asyncpg", username=role, password=password
            ).render_as_string(hide_password=False)

        yield dict(
            root=value, source=reader(source), area=reader(area), source_role=source, area_role=area
        )
    finally:
        if not conn.is_closed():
            await conn.close()
        conn = await asyncpg.connect(value.replace("postgresql+asyncpg://", "postgresql://"))
        try:
            await conn.execute(
                "DROP SCHEMA IF EXISTS uranus CASCADE; DROP SCHEMA IF EXISTS admin CASCADE"
            )
            for role in (source, area):
                if await conn.fetchval(
                    "SELECT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=$1)", role
                ):
                    await conn.execute(f"DROP OWNED BY {role}; DROP ROLE {role}")
        finally:
            await conn.close()


@pytest.fixture
async def root_connection(postgres):
    conn = await asyncpg.connect(postgres["root"].replace("postgresql+asyncpg://", "postgresql://"))
    try:
        yield conn
    finally:
        await conn.close()


@pytest.fixture
async def db_settings(settings, postgres):
    return settings.model_copy(
        update={
            "database_url": SecretStr(postgres["source"]),
            "area_database_url": SecretStr(postgres["area"]),
        }
    )
